### ISSUE TITLE
squarespace website down 

### ISSUE THREAD

**Issue by mabitter** [farm-ng/tractor#18]
**Describe the bug**
Followed link in readme to dead link : https://farm-ng.com/tractor
Trial period expired?  Ha. 

**To Reproduce**
1. Go to 'https://farm-ng.com/tractor'
2. See error

**Expected behavior**
Expected some awesome webpage that is going to attract patient venture capital from investors with altruism in their hearts, and developer-farmers that want to help build a better place for our children to grow up in through more sustainable farming practices and localizing food production.

**Screenshots**
![Screen Shot 2020-04-27 at 2 39 09 PM](https://user-images.githubusercontent.com/11846963/80408876-e1eafd80-8895-11ea-89fa-3ecc1ab945b3.png)

**Robot HW (please complete the following information):**
 - Embedded computer: [e.g. jetson xavier, nano, raspberry pi]
 - OS Info [e.g. output of ``uname -irsv``]
 - HW version or other info about the setup [e.g. 22]

**Desktop (please complete the following information):**
 - iOS
 - Chrome

**Comment by ethanrublee** [comment]
Thanks.  Yeah its not quite ready to launch :)

**Comment by ethanrublee** [comment]
We'll track this issue else where.  Coming soon.
