### ISSUE TITLE
Add linting for `option go_package` in all protos

### ISSUE THREAD

**Issue by isherman** [farm-ng/tractor#58]
`make protos` requires `option go_package = "github.com/farm_ng/genproto";` in all `protos/farm_ng_proto/tractor/v1/*.proto` files.

Enforce this via a linter or find a different approach.

**Comment by ethanrublee** [comment]
We could grep in the build script.

**Comment by ethanrublee** [comment]
i do get a lint error now:

```
protos/farm_ng_proto/tractor/v1/apriltag.proto:1:1:Files in package "farm_ng_proto.tractor.v1" have both values "github.com/farm_ng/genproto" and no value for option "go_package" and all values must be equal.
```

**Comment by isherman** [comment]
Awesome, looks like our proto linter already catches this! Closing this.
